#!/usr/bin/env Rscript

#rm(list = ls())
library("qvalue")
library("pcadapt")
library("ggplot2")

## PC adapt tutorials:
## https://bcm-uga.github.io/pcadapt/articles/pcadapt.html
## https://popgen.nescent.org/2016-01-26-SNP-selection.html#section-4-logistic-regression-linking-outliers-and-temperature
## Note: PCAdapt expects the incoming matrix to have samples in columns and loci in rows

setwd("/share/lanzarolab/users/shaghayegh/data/A.aegypti/good_ind_Q30.DP5.caling_1_maf0.03/downstream_analysis/pcAdapt")

for (i in 0:19){
  
  geno<-read.table(file =paste("A.aegypti_PcAdapt_genofile_",i, sep = ""), header = FALSE)  ## 012 genotype file generated by 012 vcftools followed by Rscript
  geno_good<-geno[,-1]
  
  write.table(geno_good, file =paste("A.aegypti_PcAdapt_genofile_",i,".pcadapt", sep =""),col.names = FALSE, row.names= FALSE, quote = FALSE)
  
  #path_to_file <- "/share/lanzarolab/users/shaghayegh/data/A.aegypti/good_ind_Q30.DP5.caling_1_maf0.03/downstream_analysis/pcAdapt/test.inputs.pcadapt"
  #filename <- read.pcadapt(path_to_file, type = "lfmm")
  
  path_to_file <- paste("/share/lanzarolab/users/shaghayegh/data/A.aegypti/good_ind_Q30.DP5.caling_1_maf0.03/downstream_analysis/pcAdapt/A.aegypti_PcAdapt_genofile_",i,".pcadapt", sep ="")
  filename <- read.pcadapt(path_to_file, type = "pcadapt")
  
  x <- pcadapt(input = filename, K = 3) 
  jpeg(file= paste("qqplot_k3/qq_plot_Pvalues_pcadapt_K3_",i,".jpeg", sep = ""), height= 500, width = 600)

  plot(x, option = "qqplot")
  dev.off()
  
  pvalues<-x$pvalues
  
  write.table(pvalues, file= paste("pcadap_pvalues_K20/A.aegypti_PcAdapt_genofile_",i,".pcadapt.K20.Pvalues.table", sep = ""),col.names = FALSE, row.names = FALSE, quote = FALSE)
  

}

###########
setwd("~/Documents/malaria_vector_reserach/input_data/a.aegypti/pcadapt")
pc_data<-read.table(file = "var_out_A.aegypti_Q30.DP5.caling_1_maf0.03_PcAdapt_12_pops_K3.txt", header = FALSE)
colnames(pc_data)<-c("snp_id","chr","pos","Pvalue")

### plot histogram of p-values and qqplot 
jpeg(file= "qqplot_Pvalues_hist_k3.jpeg", height= 500, width = 700)

aa<-pc_data[,4]
qqplot(rexp(length(aa), rate = log(10)),
-log10(aa), xlab = "Expected quantile",
pch = 19, cex = .4, main = "qqplot of adjusted P-values")
abline(0,1)

dev.off()

hist(pc_data[,4],xlab ="adjusted p-values",main = "histogram of adjusted p-values")


#### FDR correction and find the list of candidate loci
## q-values
pc_data$qval <- qvalue(pc_data$Pvalue)$qvalues
alpha <- 0.01
outliers <- pc_data[which(pc_data$qval < alpha),]


## Benjamin-Hochberg (similar to LFMM)
pc_data$padj <- p.adjust(pc_data$Pvalue,method="BH")
alpha <- 0.01
outliers_BH <- pc_data[which(padj < alpha),]


write.table(pc_data, file = "pcadapt_A.aegypti_12_pops_list_candidate_loci_FDR_0.01.txt", col.names = TRUE, row.names = FALSE, quote = FALSE)





#######################
